FROM openjdk:22
ARG JAR_FILE=image-inference-api/build/libs/image-inference-api-0.0.1-SNAPSHOT.jar


COPY ${JAR_FILE} /app.jar
ENTRYPOINT ["java","-Duser.timezone=Asia/Seoul", "-Dspring.profiles.active=dev","-jar","/app.jar"]