version: '3.8'

services:
  inference-api:
    image:
      ododieod/api
    ports:
      - "8080:8080"

  onnx-runtime:
    image:
      ododieod/onnx
    ports:
      - "8081:8000"

  tflite-runtime:
    image:
      ododieod/tflite
    ports:
      - "8082:8000"