spring:
  datasource:
    url: jdbc:mysql://mysql:3306/inference
    username: root
    password: qwerty
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: inference-group