local:
  kafka:
    bootstrap_servers: "localhost:9092"
    group_id: "onnx-group"
    topics:
      - "onnx_inference_request"

dev:
  kafka:
    bootstrap_servers: "kafka:9092"
    group_id: "onnx-group"
    topics:
      - "onnx_inference_request"