FROM python:3.9-slim

WORKDIR /app

COPY /onnx/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY /onnx .
ENV ENV=dev

CMD ["sh", "-c", "uvicorn main:app --host 0.0.0.0 --port 8000"]